# Generated by Django 4.2.15 on 2025-05-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judokas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('club', models.CharField(max_length=20)),
                ('cat_age', models.CharField(max_length=10)),
                ('cat_poids', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
