# Generated by Django 4.2.15 on 2025-05-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judokas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judokas',
            name='date_naissance',
        ),
    ]
