# Generated by Django 4.2.15 on 2025-05-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judokas', '0002_remove_judokas_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judokas',
            name='cat_age',
            field=models.CharField(choices=[('poussin', 'Poussin(ne)'), ('minime', 'Minime'), ('cadet', 'Cadet(te)'), ('junior', 'Junior'), ('senior', 'Senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='judokas',
            name='cat_poids',
            field=models.CharField(choices=[('-30', '-30 kg'), ('-36', '-36 kg'), ('-40', '-40 kg'), ('-44', '-44 kg'), ('-48', '-48 kg'), ('-52', '-52 kg'), ('-57', '-57 kg'), ('-60', '-60 kg'), ('-63', '-63 kg'), ('-66', '-66 kg'), ('-70', '-70 kg'), ('-73', '-73 kg'), ('-80', '-80 kg'), ('-100', '-100 kg'), ('+100', '+100 kg')], max_length=10),
        ),
    ]
