# Generated by Django 4.2.15 on 2025-06-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0002_alter_calendrier_date_competiton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendrier',
            name='date_competiton',
            field=models.CharField(max_length=200),
        ),
    ]
